apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
      - name: amazon
        image: 8770406568/amazon-clone
        ports:
        - containerPort: 3000  # Port your application listens on
